#!/bin/bash
set -o errexit
set -o nounset

if (( $# != 1 )); then
    echo "wrong number of arguments" >&2
    echo "usage: `basename $0` title" >&2
    exit 1 
fi
title=$1

echo -ne "\033]0;$title\007"

# http://alvinalexander.com/mac-os-x/how-set-mac-osx-terminal-title-titlebar-echo
# http://www.tech-recipes.com/rx/705/mac-os-x-change-the-terminal-window-title/
