#!/bin/bash
set -o errexit
set -o nounset

if (( $# != 1 )); then
    echo "wrong number of arguments" >&2
    echo "usage: `basename $0` title" >&2
    exit 1 
fi
title=$1

echo -ne "\033]0;$title\007"

# http://expertsxchange.blogspot.co.at/2009/02/how-to-set-terminal-title-dynamically.html

